train: /home/users/j/jacsont/Varios-OCR-files/Grountruth/my-dataset/train/images
val: /home/users/j/jacsont/Varios-OCR-files/Grountruth/my-dataset/val/images
nc: 13
names:
- MainZone:columns
- NumberingZone:page
- CustomZone:title
- MainZone
- GraphicZone:illustration
- CustomZone:impresorNum
- MarginTextZone:colophon
- CustomZone:numero_pliego
- text
- GraphicZone:ornamentation
- MusicZone
- QuireMarksZone:catchwords
- MarginTextZone:note
